#%RAML 1.0 DataType
type: object
properties:
  id?: integer
  name: string
  category?: string
  island?: string
  latitude: number
  longitude: number
  address?: string
  description?: string
  difficulty?: string
  accessibility?: string
