#%RAML 1.0 Trait
queryParameters:
  limit:
    description: Número máximo de itens a retornar
    type: integer
    required: false
    default: 10
    minimum: 1
    maximum: 100
  offset:
    description: Offset para paginação
    type: integer
    required: false
    default: 0
    minimum: 0