#%RAML 1.0 DataType
displayName: HomePageData
type: object
properties:
  featuredIslands:
    type: array
  popularLocations:
    type: array
  recommendations:
    type: array
  weatherAlerts:
    type: array

example:
  featuredIslands: []
  popularLocations: []
  recommendations: []
  weatherAlerts: []
