#%RAML 1.0 DataType
displayName: RatingResponse
type: object
properties:
  id:
    type: integer
  message:
    type: string
  newAverageRating:
    type: number
example:
  id: 1001
  message: "Rating submitted"
  newAverageRating: 4.85
